"""
Layer 1 generator: published catalog (bibliographic spine).

Row set + status come from deposit_status.csv (the canonical control file, generated by
build_deposit_status.py). All published deposits are retained — nothing is deduped;
relationships are carried as `related_to_doi`. Each row is enriched from DataCite.

Field sourcing (decided at the recon gate, refined for the no-dedup model):
  - Title, Authors, URL, publicationYear   <- DataCite
  - Version, Version Date                   <- seed inventory.csv (precise; freshness backstop)
  - Study ID, Archive, status, seed DOI,
    resolve_doi_for_datacite, related_to_doi <- deposit_status.csv

Resolution per row uses resolve_doi_for_datacite as the starting value, with the documented
fallback chain at runtime:  resolve_doi (ICPSR-form as-is / E-form base)  ->  ICPSR{study_id}
twin  if the first 404s. The DOI that actually resolved is recorded in `resolve_doi_used`.

A `version_check` column compares seed vs DataCite version for ICPSR-form resolutions (the
seed-freshness backstop); E-form base records report V0 and stay seed-authoritative.

Topic Folder / Geographies / Date Range / Unique ID(s) / smallest-geo are LEFT EMPTY here —
Layer 2's job, joined in reconcile.py.

Output: data/published_catalog.csv (+ stdout summary). Read-only HTTP GET against DataCite.
"""

from __future__ import annotations

import csv
import re
import sys
import time
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parent
DEPOSIT_CSV = REPO / "deposit_status.csv"
SEED_CSV = REPO.parent / "usage-metrics" / "inventory.csv"
OUT_CSV = REPO / "data" / "published_catalog.csv"
API = "https://api.datacite.org/dois/"

TITLE_PREFIXES = (
    "National Neighborhood Data Archive (NaNDA): ",
    "National Neighborhood Data Archive: ",
)

OUT_COLUMNS = [
    "study_id", "archive", "deposit_via", "status", "title", "version", "version_date",
    "version_date_flag", "seed_doi", "resolve_doi_used", "related_to_doi", "url", "authors",
    "publication_year", "datacite_version", "version_check", "datacite_status", "note",
    # Layer 2 fills these in reconcile.py:
    "topic_folder", "geographies", "date_range", "unique_ids", "smallest_geo",
]


def strip_title_prefix(title: str) -> str:
    t = (title or "").strip()
    for pre in TITLE_PREFIXES:
        if t.startswith(pre):
            return t[len(pre):].strip()
    return t


def major_version(v: str) -> int | None:
    m = re.search(r"(\d+)", str(v) or "")
    return int(m.group(1)) if m else None


def is_icpsr_form(doi: str) -> bool:
    return bool(re.search(r"/ICPSR\d+", doi, re.IGNORECASE))


def normalize_author(creator: dict) -> str:
    given = (creator.get("givenName") or "").strip()
    family = (creator.get("familyName") or "").strip()
    if given and family:
        return f"{given} {family}"
    name = (creator.get("name") or "").strip()
    if "," in name:  # "Last, First" -> "First Last"
        last, first = (p.strip() for p in name.split(",", 1))
        return f"{first} {last}".strip()
    return name


def _get(doi: str):
    return requests.get(API + requests.utils.quote(doi, safe=""),
                        headers={"Accept": "application/vnd.api+json"}, timeout=30)


def resolve(resolve_doi: str, study_id: str, version: str) -> tuple[str, dict | None, str]:
    """Run the fallback chain. Return (status, attributes|None, resolved_doi)."""
    try:
        r = _get(resolve_doi)
        if r.status_code == 200:
            return "resolved", r.json()["data"]["attributes"], resolve_doi
        # Fallback: try the ICPSR-form twin (covers any E-form whose base 404s).
        mv = major_version(version) or 1
        twin = f"10.3886/ICPSR{study_id}.v{mv}"
        if twin != resolve_doi:
            r2 = _get(twin)
            if r2.status_code == 200:
                return "resolved-via-twin", r2.json()["data"]["attributes"], twin
        return "UNRESOLVED", None, resolve_doi
    except requests.RequestException as exc:
        return f"ERROR:{type(exc).__name__}", None, resolve_doi


def build_row(dep: dict, seed: dict) -> dict:
    study_id = dep["study_id"]
    resolve_doi = dep["resolve_doi_for_datacite"].strip()
    version = (seed.get("version") or "").strip()
    version_date = (seed.get("version_date") or "").strip()

    status_dc, attr, resolved_doi = resolve(resolve_doi, study_id, version)
    attr = attr or {}

    titles = attr.get("titles") or []
    dc_title = strip_title_prefix(titles[0]["title"]) if titles else ""
    creators = attr.get("creators") or []
    authors = "; ".join(a for a in (normalize_author(c) for c in creators) if a)
    dc_version = attr.get("version") or ""

    if not attr:
        version_check = "datacite-unresolved"
    elif is_icpsr_form(resolved_doi):
        sv, dv = major_version(version), major_version(dc_version)
        version_check = "match" if sv is not None and sv == dv else \
            f"MISMATCH seed={version} datacite={dc_version}"
    else:
        version_check = f"E-style: datacite={dc_version or 'V0'} (seed authoritative)"

    return {
        "study_id": study_id,
        "archive": dep.get("archive", ""),
        "deposit_via": dep.get("deposit_via", ""),
        "status": dep.get("status", ""),
        "title": dc_title or strip_title_prefix(seed.get("title", "")),
        "version": version,
        "version_date": version_date,
        "version_date_flag": "BLANK_IN_SEED" if not version_date else "",
        "seed_doi": dep.get("seed_doi", ""),
        "resolve_doi_used": resolved_doi,
        "related_to_doi": dep.get("related_to_doi", ""),
        "url": attr.get("url", "") or "",          # URL from DataCite
        "authors": authors,
        "publication_year": attr.get("publicationYear", "") or "",
        "datacite_version": dc_version,
        "version_check": version_check,
        "datacite_status": status_dc,
        "note": dep.get("note", ""),
        "topic_folder": "", "geographies": "", "date_range": "",
        "unique_ids": "", "smallest_geo": "",
    }


def main() -> int:
    if not DEPOSIT_CSV.exists():
        print(f"FATAL: {DEPOSIT_CSV} missing. Run build_deposit_status.py first.", file=sys.stderr)
        return 2
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)

    with DEPOSIT_CSV.open("r", encoding="utf-8-sig", newline="") as fh:
        deposits = list(csv.DictReader(fh))
    with SEED_CSV.open("r", encoding="utf-8-sig", newline="") as fh:
        seed_by_id = {r["study_id"].strip(): r for r in csv.DictReader(fh)}

    print(f"Deposit rows: {len(deposits)}. Querying DataCite...\n")
    rows = []
    for i, dep in enumerate(deposits, 1):
        seed = seed_by_id.get(dep["study_id"], {})
        row = build_row(dep, seed)
        rows.append(row)
        print(f"  [{i:>2}/{len(deposits)}] {row['study_id']:>7}  {row['datacite_status']:<17} "
              f"v={row['version'] or '?':<6} {row['version_check']}")
        time.sleep(1)  # polite

    with OUT_CSV.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=OUT_COLUMNS)
        w.writeheader()
        w.writerows(rows)

    unresolved = [r for r in rows if r["datacite_status"].startswith(("UNRESOLVED", "ERROR"))]
    via_twin = [r for r in rows if r["datacite_status"] == "resolved-via-twin"]
    mismatches = [r for r in rows if r["version_check"].startswith("MISMATCH")]
    blank_dates = [r for r in rows if r["version_date_flag"]]
    no_authors = [r for r in rows if not r["authors"]]
    related = [r for r in rows if r["related_to_doi"]]

    print("\n" + "=" * 70)
    print("LAYER 1 - PUBLISHED CATALOG  (row set: deposit_status.csv)")
    print("=" * 70)
    print(f"Rows written              : {len(rows)}  ->  {OUT_CSV}")
    print(f"Resolved                  : {sum(1 for r in rows if r['datacite_status']=='resolved')}")
    print(f"Resolved via twin fallback: {len(via_twin)}")
    print(f"UNRESOLVED / error        : {len(unresolved)}")
    for r in unresolved:
        print(f"      {r['study_id']}  {r['seed_doi']}  ({r['datacite_status']})")
    print(f"Version seed-vs-DataCite MISMATCH (ICPSR-form): {len(mismatches)}")
    for r in mismatches:
        print(f"      {r['study_id']}  {r['version_check']}")
    print(f"Blank version_date in seed (flagged): {len(blank_dates)}  "
          f"({', '.join(r['study_id'] for r in blank_dates)})")
    print(f"Rows with no DataCite authors       : {len(no_authors)}  "
          f"({', '.join(r['study_id'] for r in no_authors)})")
    print(f"Rows carrying related_to_doi        : {len(related)}  "
          f"({', '.join(r['study_id'] for r in related)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
